@apiUrl = http://localhost:5008/api
@customerId = C69903F5-E6FF-4B85-9CA2-7C95C17A82B8
@orderId = C69903F5-E6FF-4B85-9CA2-7C95C17A82B8
@customerEmail = my@email.com

### Create a customer
POST {{apiUrl}}/customers
Content-Type: application/json

{
  "fullName": "Mikolaj Jankowski",
  "birthDate": "1990-01-01",
  "email": "{{customerEmail}}",
  "street": "Wall Street",
  "houseNumber": "10A",
  "flatNumber": "1",
  "country": "PL",
  "postalCode": "69-100"
}


### Create an order
POST {{apiUrl}}/orders
Content-Type: application/json

{
  "street": "Fifth Avenue",
  "postalCode": "10037",
  "customerId": "{{customerId}}",
  "products": [
    {
      "productId": 1,
      "productName": "Bike",
      "price": 100,
      "currency": "USD",
      "quantity": 2
    }
  ]
}

### Get customer
GET {{apiUrl}}/customers?Email={{customerEmail}}
Content-Type: application/json; charset=utf-8

### Get order
GET {{apiUrl}}/orders?Id={{orderId}}
Content-Type: application/json; charset=utf-8

### Change e-mail
POST {{apiUrl}}/customers/change-email
Content-Type: application/json

{
  "oldEmail": "{{customerEmail}}",
  "newEmail": "somone@yourdomain.com"
}

### Verify e-mail
POST {{apiUrl}}/customers/verify-email
Content-Type: application/json

{
  "email": "{{customerEmail}}"
}

