@apiUrl = http://localhost:5008
@customerId = 1d31ae71-0bea-4cdd-869f-b53a79849965

### Create a customer
POST {{apiUrl}}/customer
Content-Type: application/json

{
  "fullName": "Mikolaj Jankowski",
  "birthDate": "1990-01-01",
  "email": "my@email.com",
  "street": "Wall Street",
  "houseNumber": "10A",
  "flatNumber": "1",
  "country": "PL",
  "postalCode": "69-100"
}


### Create an order
POST {{apiUrl}}/order
Content-Type: application/json

{
  "street": "Fifth Avenue",
  "postalCode": "10037",
  "customerId": "{{customerId}}",
  "products": [
    {
      "productId": 1,
      "productName": "Bike",
      "price": 100,
      "currency": "USD",
      "quantity": 2
    }
  ]
}
