@apiUrl = http://localhost:5008
@customerId = 9b19b89f-d342-467e-beaa-d009d6d5750c
@customerEmail = my@email.com

### Create a customer
POST {{apiUrl}}/customer
Content-Type: application/json

{
  "fullName": "Mikolaj Jankowski",
  "birthDate": "1990-01-01",
  "email": "my@email.com",
  "street": "Wall Street",
  "houseNumber": "10A",
  "flatNumber": "1",
  "country": "PL",
  "postalCode": "69-100"
}


### Create an order
POST {{apiUrl}}/order
Content-Type: application/json

{
  "street": "Fifth Avenue",
  "postalCode": "10037",
  "customerId": "{{customerId}}",
  "products": [
    {
      "productId": 1,
      "productName": "Bike",
      "price": 100,
      "currency": "USD",
      "quantity": 2
    }
  ]
}

### Get customer
GET {{apiUrl}}/Customer?Email={{customerEmail}}
Content-Type: application/json; charset=utf-8

### Change e-mail
POST {{apiUrl}}/Customer/change-email
Content-Type: application/json

{
  "oldEmail": "{{customerEmail}}",
  "newEmail": "somone@yourdomain.com"
}

### Verify e-mail
POST {{apiUrl}}/Customer/verify-email
Content-Type: application/json

{
  "email": "{{customerEmail}}"
}

