@apiUrl = http://localhost:5008
@customerId = 57AC8E47-87C3-47BC-8494-9FEC2140D3C1
@customerEmail = my@email.com

### Create a customer
POST {{apiUrl}}/customer
Content-Type: application/json

{
  "fullName": "Mikolaj Jankowski",
  "birthDate": "1990-01-01",
  "email": "my@email.com",
  "street": "Wall Street",
  "houseNumber": "10A",
  "flatNumber": "1",
  "country": "PL",
  "postalCode": "69-100"
}


### Create an order
POST {{apiUrl}}/order
Content-Type: application/json

{
  "street": "Fifth Avenue",
  "postalCode": "10037",
  "customerId": "{{customerId}}",
  "products": [
    {
      "productId": 1,
      "productName": "Bike",
      "price": 100,
      "currency": "USD",
      "quantity": 2
    }
  ]
}

### Get customer
GET {{apiUrl}}/Customer?Email={{customerEmail}}
Content-Type: application/json; charset=utf-8
